# Generated by Django 3.2 on 2023-03-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230328_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='6c28a84c-6bb2-4e4a-8a68-66d1cf7faaad', max_length=255, verbose_name='Код подтверждения'),
        ),
    ]
